import type { Theme } from "@earendil-works/pi-coding-agent";
import type { Container, TUI } from "@earendil-works/pi-tui";
import { createToolPreviewWidget } from "./tool-preview.ts";

export function createGrepPreviewWidget(tui: TUI, cwd: string, theme: Theme): Container {
	return createToolPreviewWidget(tui, cwd, theme, "grep", [
		{
			name: "grep",
			sampleTitle: "Shared Base, Multiple Files",
			args: { queries: [["-n", "-e", "How", "-e", "Context", "README.md", "src/extensions/search/README.md"]] },
			argText: "-n -e How -e Context README.md src/extensions/search/README.md",
			result: [
				"base /Users/shanepadgett/.local/share/tau-agent/references/",
				"opencode-dynamic-context-pruning/README.md (239 lines)",
				"31: ## How It Works",
				"35: ### Compress",
				"46: ### Deduplication",
				"50: ### Purge Errors",
				"pi-model-reference-compactor/README.md (297 lines)",
				"9: ## What pi-mrc optimizes",
				"82: ## How MRC compaction works",
				"99: ## Context shape",
				"129: ## Reference lifecycle",
				"145: ## Source recoverability",
				"166: ## `mrc_lookup`",
				"286: ## Design principles",
				"",
				"pi-vcc/README.md (219 lines)",
				"13: ## Why pi-vcc",
				"40: ## Features",
				"86: ### How compaction works",
				"90: ### Compacted message structure",
				"142: ## Recall (Lossless History)",
				"188: ## Pipeline",
				"",
				"src/extensions/search/README.md (7 lines)",
				"1: # Tau Search",
				"5: `workingMemory` can prune stale or forgotten search evidence and enables `forget`.",
			].join("\n"),
		},
		{
			name: "grep",
			sampleTitle: "Single File, No Base Line",
			args: { queries: [["-n", "workingMemory", "src/extensions/search/README.md"]] },
			argText: "-n workingMemory src/extensions/search/README.md",
			result: [
				"src/extensions/search/README.md (7 lines)",
				"5: `workingMemory` can prune stale or forgotten search evidence and enables `forget`.",
			].join("\n"),
		},
		{
			name: "grep",
			sampleTitle: "No Matches",
			args: { queries: [["-n", "doesNotExist", "src/extensions/search/README.md"]] },
			argText: "-n doesNotExist src/extensions/search/README.md",
			result: "No matches",
		},
		{
			name: "grep",
			sampleTitle: "Context Lines",
			args: { queries: [["-n", "-C", "2", "createReadToolDefinition", "src/extensions/explore/read.ts"]] },
			argText: "-n -C 2 createReadToolDefinition src/extensions/explore/read.ts",
			result: [
				"src/extensions/explore/read.ts (42 lines)",
				'1- import { Type } from "typebox";',
				"2-",
				"3: export function createReadToolDefinition() {",
				"4- \treturn {",
				'5- \t\tname: "read",',
			].join("\n"),
		},
		{
			name: "grep",
			sampleTitle: "Context Only",
			args: {
				queries: [["-n", "-C", "2", "createReadToolDefinition", "src/extensions/explore/read.ts"]],
				contextOnly: true,
			},
			argText: "-n -C 2 createReadToolDefinition src/extensions/explore/read.ts contextOnly",
			result: [
				"src/extensions/explore/read.ts (42 lines)",
				'1- import { Type } from "typebox";',
				"2-",
				"4- \treturn {",
				'5- \t\tname: "read",',
			].join("\n"),
		},
		{
			name: "grep",
			sampleTitle: "Max Per File",
			args: { queries: [["-n", "search", "src/extensions/search/index.ts"]], maxPerFile: 2 },
			argText: "-n search src/extensions/search/index.ts maxPerFile=2",
			result: [
				"src/extensions/search/index.ts (180 lines)",
				"25: export const searchExtension = defineExtension({",
				"38: registerTool(createSearchReadTool())",
				"… omitted 6 matches in file (maxPerFile 2)",
			].join("\n"),
		},
		{
			name: "grep",
			sampleTitle: "Max Line Length",
			args: { queries: [["-n", "workingMemory", "src/extensions/search/README.md"]], maxLineLength: 72 },
			argText: "-n workingMemory src/extensions/search/README.md maxLineLength=72",
			result: [
				"src/extensions/search/README.md (7 lines)",
				"5: `workingMemory` can prune stale or forgotten search evidence and enables…",
			].join("\n"),
		},
		{
			name: "grep",
			sampleTitle: "Multiple Queries",
			args: {
				queries: [
					["-n", "Tau Search", "src/extensions/search/README.md"],
					["-n", "searchExtension", "src/extensions/search/index.ts"],
				],
			},
			argText: "2 queries",
			result: [
				"query 1 -n Tau Search src/extensions/search/README.md",
				"src/extensions/search/README.md (7 lines)",
				"1: # Tau Search",
				"query 2 -n searchExtension src/extensions/search/index.ts",
				"src/extensions/search/index.ts (180 lines)",
				"25: export const searchExtension = defineExtension({",
			].join("\n"),
		},
		{
			name: "grep",
			sampleTitle: "Hidden No Ignore",
			args: { queries: [["-n", "--hidden", "--no-ignore", "tool-preview", ".pi/extensions"]] },
			argText: "-n --hidden --no-ignore tool-preview .pi/extensions",
			result: [
				".pi/extensions/tool-preview/index.ts (69 lines)",
				'10: const COMMAND = "tool-preview";',
				'21: { value: "clear", label: "clear", description: "Hide the preview widget" },',
			].join("\n"),
		},
		{
			name: "grep",
			sampleTitle: "Limit Hit",
			args: { queries: [["-n", "evidence", "src/extensions/search"]], limit: 5 },
			argText: "-n evidence src/extensions/search limit=5",
			result: [
				"src/extensions/search/context-pruning.ts (211 lines)",
				"24: export function pruneSearchContext(",
				"68: const evidence = parseSearchEvidence(message)",
				"94: markEvidenceOutdated(evidence)",
				"src/extensions/search/evidence.ts (92 lines)",
				"11: export interface SearchEvidence {",
				"31: export function createSearchEvidence(",
				"… omitted 42 matches (limit 5)",
			].join("\n"),
		},
		{
			name: "grep",
			sampleTitle: "Invalid Regex Error",
			args: { queries: [["-n", "[workingMemory", "src/extensions/search/README.md"]] },
			argText: "-n [workingMemory src/extensions/search/README.md",
			result: ["regex parse error: unclosed character class", "pattern: [workingMemory"].join("\n"),
			isError: true,
		},
	]);
}
