import type { Theme } from "@earendil-works/pi-coding-agent";
import type { Container, TUI } from "@earendil-works/pi-tui";
import { createToolPreviewWidget } from "./tool-preview.ts";

export function createLsPreviewWidget(tui: TUI, cwd: string, theme: Theme): Container {
	return createToolPreviewWidget(tui, cwd, theme, "ls", [
		{
			name: "ls",
			sampleTitle: "Depth 1",
			args: { paths: ["src/extensions"], depth: 1, limit: 20 },
			argText: "src/extensions depth=1 limit=20",
			result: ["explore/", "patch/", "search/"].join("\n"),
			agentResult: ["explore/", "patch/", "search/"].join("\n"),
		},
		{
			name: "ls",
			sampleTitle: "Depth 2",
			args: { paths: ["src/extensions"], depth: 2, limit: 40 },
			argText: "src/extensions depth=2 limit=40",
			result: [
				"explore/",
				"  find.ts",
				"  grep.ts",
				"  index.ts",
				"  ls.ts",
				"  read.ts",
				"  tools/",
				"patch/",
				"  executor.ts",
				"  index.ts",
				"  matcher.ts",
				"  parser.ts",
				"search/",
				"  context-pruning.ts",
				"  evidence.ts",
				"  find.ts",
				"  grep.ts",
				"  index.ts",
				"  ls.ts",
				"  read.ts",
				"  README.md",
				"  render-state.ts",
			].join("\n"),
			agentResult: [
				"explore/find.ts,grep.ts,index.ts,ls.ts,read.ts",
				"  tools/",
				"patch/executor.ts,index.ts,matcher.ts,parser.ts",
				"search/context-pruning.ts,evidence.ts,find.ts,grep.ts,index.ts,ls.ts,read.ts,README.md,render-state.ts",
			].join("\n"),
		},
		{
			name: "ls",
			sampleTitle: "Depth 3",
			args: { paths: ["src/extensions"], depth: 3, limit: 50 },
			argText: "src/extensions depth=3 limit=50",
			result: [
				"explore/",
				"  index.ts",
				"  README.md",
				"  tools/",
				"    find.ts",
				"    grep.ts",
				"    ls.ts",
				"    read.ts",
				"patch/",
				"  executor.ts",
				"  index.ts",
				"  matcher.ts",
				"  parser.ts",
				"search/",
				"  context-pruning.ts",
				"  evidence.ts",
				"  find.ts",
				"  grep.ts",
				"  index.ts",
				"  ls.ts",
				"  read.ts",
				"  README.md",
				"  render-state.ts",
			].join("\n"),
			agentResult: [
				"explore/index.ts,README.md",
				"  tools/find.ts,grep.ts,ls.ts,read.ts",
				"patch/executor.ts,index.ts,matcher.ts,parser.ts",
				"search/context-pruning.ts,evidence.ts,find.ts,grep.ts,index.ts,ls.ts,read.ts,README.md,render-state.ts",
			].join("\n"),
		},
		{
			name: "ls",
			sampleTitle: "Depth 4",
			args: { paths: ["src/extensions"], depth: 4, limit: 60 },
			argText: "src/extensions depth=4 limit=60",
			result: [
				"explore/",
				"  index.ts",
				"  README.md",
				"  tools/",
				"    find.ts",
				"    grep.ts",
				"    ls.ts",
				"    read.ts",
				"patch/",
				"  executor.ts",
				"  index.ts",
				"  matcher.ts",
				"  parser.ts",
				"search/",
				"  context-pruning.ts",
				"  evidence.ts",
				"  find.ts",
				"  grep.ts",
				"  index.ts",
				"  ls.ts",
				"  read.ts",
				"  README.md",
				"  render-state.ts",
				"  fixtures/",
				"    nested/",
				"      case-a.ts",
				"      case-b.ts",
			].join("\n"),
			agentResult: [
				"explore/index.ts,README.md",
				"  tools/find.ts,grep.ts,ls.ts,read.ts",
				"patch/executor.ts,index.ts,matcher.ts,parser.ts",
				"search/context-pruning.ts,evidence.ts,find.ts,grep.ts,index.ts,ls.ts,read.ts,README.md,render-state.ts",
				"  fixtures/",
				"    nested/case-a.ts,case-b.ts",
			].join("\n"),
		},
		{
			name: "ls",
			sampleTitle: "Multiple Roots",
			args: { paths: ["src/extensions/explore", "docs/plans"], depth: 2, limit: 30 },
			argText: "src/extensions/explore docs/plans depth=2 limit=30",
			result: [
				"src/extensions/explore/",
				"  index.ts",
				"  README.md",
				"  tools/",
				"    find.ts",
				"    grep.ts",
				"    ls.ts",
				"    read.ts",
				"docs/plans/",
				"  explore-ui-turn-simulation.md",
				"  explore.working.md",
			].join("\n"),
			agentResult: [
				"src/extensions/explore/index.ts,README.md",
				"  tools/find.ts,grep.ts,ls.ts,read.ts",
				"docs/plans/explore-ui-turn-simulation.md,explore.working.md",
			].join("\n"),
		},
		{
			name: "ls",
			sampleTitle: "Empty Directory",
			args: { paths: ["src/extensions/explore/fixtures/empty"], depth: 1, limit: 20 },
			argText: "src/extensions/explore/fixtures/empty depth=1 limit=20",
			result: ["src/extensions/explore/fixtures/empty/", "  [empty]"].join("\n"),
			agentResult: "src/extensions/explore/fixtures/empty/ [empty]",
		},
		{
			name: "ls",
			sampleTitle: "Single File",
			args: { paths: ["src/extensions/explore/index.ts"], depth: 1, limit: 20 },
			argText: "src/extensions/explore/index.ts",
			result: "src/extensions/explore/index.ts",
			agentResult: "src/extensions/explore/index.ts",
		},
		{
			name: "ls",
			sampleTitle: "All Hidden Entries",
			args: { paths: ["src/extensions/explore"], depth: 2, all: true, limit: 30 },
			argText: "src/extensions/explore depth=2 all limit=30",
			result: [
				"src/extensions/explore/",
				"  .draft-notes.md",
				"  index.ts",
				"  README.md",
				"  .fixtures/",
				"    hidden-case.ts",
				"  tools/",
				"    find.ts",
				"    grep.ts",
			].join("\n"),
			agentResult: [
				"src/extensions/explore/.draft-notes.md,index.ts,README.md",
				"  .fixtures/hidden-case.ts",
				"  tools/find.ts,grep.ts",
			].join("\n"),
		},
		{
			name: "ls",
			sampleTitle: "Long Listing",
			args: { paths: ["src/extensions/explore"], depth: 1, long: true, limit: 20 },
			argText: "src/extensions/explore depth=1 long limit=20",
			result: [
				"src/extensions/explore/",
				"  index.ts 1.6 KB 2026-06-28",
				"  README.md 0.7 KB 2026-06-28",
				"  tools/ dir 2026-06-28",
			].join("\n"),
			agentResult: [
				"src/extensions/explore/index.ts(1.6KB,2026-06-28),README.md(0.7KB,2026-06-28)",
				"  tools/(dir,2026-06-28)",
			].join("\n"),
		},
		{
			name: "ls",
			sampleTitle: "Limit Hit",
			args: { paths: ["src/extensions/search"], depth: 2, limit: 8 },
			argText: "src/extensions/search depth=2 limit=8",
			result: [
				"src/extensions/search/",
				"  context-pruning.ts",
				"  evidence.ts",
				"  find.ts",
				"  forget.ts",
				"  grep.ts",
				"  index.ts",
				"  ls.ts",
				"  memory-messages.ts",
				"… omitted 13 entries (limit 8)",
			].join("\n"),
			agentResult: [
				"src/extensions/search/context-pruning.ts,evidence.ts,find.ts,forget.ts,grep.ts,index.ts,ls.ts,memory-messages.ts",
				"… omitted 13 entries (limit 8)",
			].join("\n"),
		},
		{
			name: "ls",
			sampleTitle: "Missing Path Error",
			args: { paths: ["src/extensions/missing"], depth: 1, limit: 20 },
			argText: "src/extensions/missing depth=1 limit=20",
			result: "Path not found: src/extensions/missing",
			isError: true,
		},
	]);
}
