import type { Theme } from "@earendil-works/pi-coding-agent";
import type { Container, TUI } from "@earendil-works/pi-tui";
import { createAstToolPreviewWidget } from "./ast-tool-preview.ts";

export function createOutlinePreviewWidget(tui: TUI, cwd: string, theme: Theme): Container {
	return createAstToolPreviewWidget(tui, cwd, theme, "outline", [
		{
			name: "outline",
			sampleTitle: "File Outline",
			args: { path: "packages/agent/extensions/explore/path-display.ts" },
			target: "packages/agent/extensions/explore/path-display.ts",
			result: [
				"imports",
				'1-1: import { isAbsolute, relative, resolve } from "node:path";',
				"",
				"declarations",
				"3-5(1): export function stripLeadingAt(value: string): string",
				"7-9(2): export function toSlashPath(value: string): string",
				"11-15(3): export function resolveExplorePath(cwd: string, input: string): string",
				"17-22(4): export function pathResolutionError(error: unknown, input: string): Error",
				"24-27(5): export function isWithinPath(parent: string, child: string): boolean",
				"29-36(6): export function formatPathForDisplay(absolutePath: string, cwd: string): string",
				"38-41(7): export function relativeSlash(from: string, to: string): string",
			].join("\n"),
			declarationCount: 7,
			returnedBytes: 780,
			avoidedBytes: 720,
		},
		{
			name: "outline",
			sampleTitle: "Package Directory",
			args: { path: "packages/agent/extensions/explore", includePrivate: true },
			target: "packages/agent/extensions/explore",
			options: "[private]",
			result: [
				"packages/agent/extensions/explore/index.ts",
				"",
				"imports",
				'1-1: import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";',
				"",
				"declarations",
				"21-113(1): export default function exploreExtension(pi: ExtensionAPI): void",
				"",
				"packages/agent/extensions/explore/ls.ts",
				"",
				"declarations",
				"51-113(2): export function createLsTool(rowState: ToolRowStateStore)",
			].join("\n"),
			declarationCount: 2,
			returnedBytes: 620,
			avoidedBytes: 8200,
		},
		{
			name: "outline",
			sampleTitle: "Recursive Subtree",
			args: { path: "packages/agent/extensions/explore", recursive: true },
			target: "packages/agent/extensions/explore",
			options: "[recursive]",
			result: [
				"packages/agent/extensions/explore/find.ts",
				"",
				"declarations",
				"78-147(1): export function createFindTool(rowState: ToolRowStateStore)",
				"",
				"packages/agent/extensions/explore/grep.ts",
				"",
				"declarations",
				"700-749(2): export function createGrepTool(rowState: ToolRowStateStore)",
			].join("\n"),
			declarationCount: 24,
			returnedBytes: 4200,
			avoidedBytes: 144_000,
		},
		{
			name: "outline",
			sampleTitle: "Exact Names Filter",
			args: {
				path: "packages/agent/extensions/explore/path-display.ts",
				names: ["formatPathForDisplay", "resolveExplorePath"],
			},
			target: "packages/agent/extensions/explore/path-display.ts",
			options: "[names=formatPathForDisplay,resolveExplorePath]",
			result: [
				"declarations",
				"11-15(1): export function resolveExplorePath(cwd: string, input: string): string",
				"29-36(2): export function formatPathForDisplay(absolutePath: string, cwd: string): string",
			].join("\n"),
			declarationCount: 2,
			returnedBytes: 220,
			avoidedBytes: 1280,
		},
		{
			name: "outline",
			sampleTitle: "No Declarations",
			args: { path: "packages/agent/extensions/explore/path-display.ts", names: ["doesNotExist"] },
			target: "packages/agent/extensions/explore/path-display.ts",
			options: "[names=doesNotExist]",
			result: "No matching declarations",
			declarationCount: 0,
			returnedBytes: 24,
			avoidedBytes: 1476,
		},
		{
			name: "outline",
			sampleTitle: "Missing Path Error",
			args: { path: "packages/agent/extensions/missing.ts" },
			target: "packages/agent/extensions/missing.ts",
			result: "Path not found: packages/agent/extensions/missing.ts",
			declarationCount: 0,
			returnedBytes: 52,
			avoidedBytes: 0,
			isError: true,
		},
	]);
}
