import type { Theme } from "@earendil-works/pi-coding-agent";
import type { Container, TUI } from "@earendil-works/pi-tui";
import { createToolPreviewWidget } from "./tool-preview.ts";

export function createReadPreviewWidget(tui: TUI, cwd: string, theme: Theme): Container {
	return createToolPreviewWidget(tui, cwd, theme, "read", [
		{
			name: "read",
			sampleTitle: "Whole File",
			args: { path: "src/extensions/explore/read.ts" },
			argText: "src/extensions/explore/read.ts",
			result: [
				'import { Type } from "typebox";',
				"",
				"export function createReadToolDefinition() {",
				"\treturn {",
				'\t\tname: "read",',
				"\t};",
				"}",
			].join("\n"),
		},
		{
			name: "read",
			sampleTitle: "Line Range",
			args: { path: "src/extensions/explore/read.ts", offset: 3, limit: 4 },
			argText: "src/extensions/explore/read.ts:3-6",
			agentResult: [
				"export function createReadToolDefinition() {",
				"\treturn {",
				'\t\tname: "read",',
				"\t};",
				"",
				"[1 more lines in file. Use offset=7 to continue.]",
			].join("\n"),
			result: [
				"export function createReadToolDefinition() {",
				"\treturn {",
				'\t\tname: "read",',
				"\t};",
				"",
				"[1 more lines in file. Use offset=7 to continue.]",
			].join("\n"),
		},
		{
			name: "read",
			sampleTitle: "Range Near EOF",
			args: { path: "src/extensions/explore/read.ts", offset: 5, limit: 20 },
			argText: "src/extensions/explore/read.ts:5-24",
			result: ['\t\tname: "read",', "\t};", "}"].join("\n"),
		},
		{
			name: "read",
			sampleTitle: "Huge File Truncated",
			args: { path: "src/extensions/search/context-pruning.ts" },
			argText: "src/extensions/search/context-pruning.ts",
			agentResult: [
				'import type { Message } from "@earendil-works/pi-coding-agent";',
				'import { parseSearchEvidence } from "./evidence.ts";',
				"",
				"export function pruneSearchContext(messages: Message[]): Message[] {",
				"\tconst seen = new Set<string>();",
				"\t// …",
				"}",
				"",
				"[Showing lines 1-2000 of 2843. Use offset=2001 to continue.]",
			].join("\n"),
			result: [
				'import type { Message } from "@earendil-works/pi-coding-agent";',
				'import { parseSearchEvidence } from "./evidence.ts";',
				"",
				"export function pruneSearchContext(messages: Message[]): Message[] {",
				"\tconst seen = new Set<string>();",
				"\t// …",
				"}",
				"",
				"[Showing lines 1-2000 of 2843. Use offset=2001 to continue.]",
				"[Truncated: showing 2000 of 2843 lines (2000 line limit)]",
			].join("\n"),
		},
		{
			name: "read",
			sampleTitle: "Byte Limit Truncated",
			args: { path: "node_modules/zod/v4/core/schemas.cjs" },
			argText: "node_modules/zod/v4/core/schemas.cjs",
			agentResult: [
				'"use strict";',
				"var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {",
				"    if (k2 === undefined) k2 = k;",
				"    // …",
				"",
				"[Showing lines 1-1404 of 2271 (50.0KB limit). Use offset=1405 to continue.]",
			].join("\n"),
			result: [
				'"use strict";',
				"var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {",
				"    if (k2 === undefined) k2 = k;",
				"    // …",
				"",
				"[Showing lines 1-1404 of 2271 (50.0KB limit). Use offset=1405 to continue.]",
				"[Truncated: 1404 lines shown (50.0KB limit)]",
			].join("\n"),
		},
		{
			name: "read",
			sampleTitle: "First Line Exceeds Limit",
			args: { path: "dist/one-line-bundle.js" },
			argText: "dist/one-line-bundle.js",
			agentResult:
				"[Line 1 is 1.4MB, exceeds 50.0KB limit. Use bash: sed -n '1p' dist/one-line-bundle.js | head -c 51200]",
			result: [
				"[Line 1 is 1.4MB, exceeds 50.0KB limit. Use bash: sed -n '1p' dist/one-line-bundle.js | head -c 51200]",
				"[First line exceeds 50.0KB limit]",
			].join("\n"),
		},
		{
			name: "read",
			sampleTitle: "Missing File Error",
			args: { path: "src/extensions/explore/missing.ts" },
			argText: "src/extensions/explore/missing.ts",
			result: "File not found: src/extensions/explore/missing.ts",
			isError: true,
		},
		{
			name: "read",
			sampleTitle: "Directory Path Error",
			args: { path: "src/extensions/explore" },
			argText: "src/extensions/explore",
			result: "Path is a directory: src/extensions/explore",
			isError: true,
		},
		{
			name: "read",
			sampleTitle: "Offset Beyond EOF Error",
			args: { path: "src/extensions/explore/read.ts", offset: 99, limit: 4 },
			argText: "src/extensions/explore/read.ts:99-102",
			result: "Offset 99 is beyond end of file (7 lines total)",
			isError: true,
		},
		{
			name: "read",
			sampleTitle: "Image File",
			args: { path: "assets/logo.png" },
			argText: "assets/logo.png",
			result: "Read image file [image/png]",
		},
	]);
}
