import type { Theme } from "@earendil-works/pi-coding-agent";
import type { Container, TUI } from "@earendil-works/pi-tui";
import { createAstToolPreviewWidget } from "./ast-tool-preview.ts";

export function createSymbolPreviewWidget(tui: TUI, cwd: string, theme: Theme): Container {
	return createAstToolPreviewWidget(tui, cwd, theme, "symbol", [
		{
			name: "symbol",
			sampleTitle: "Signature View",
			args: { locators: [6], view: "signature" },
			target: "path-display.ts: formatPathForDisplay",
			options: "[signature]",
			result: [
				"29-36(6): formatPathForDisplay",
				"export function formatPathForDisplay(absolutePath: string, cwd: string): string",
			].join("\n"),
			declarationCount: 1,
			returnedBytes: 120,
			avoidedBytes: 280,
		},
		{
			name: "symbol",
			sampleTitle: "Signature With Docs",
			args: { locators: [6], view: "signatureWithDocs" },
			target: "path-display.ts: formatPathForDisplay",
			options: "[signatureWithDocs]",
			result: [
				"29-36(6): formatPathForDisplay",
				"/** Format an absolute path relative to cwd when possible. */",
				"export function formatPathForDisplay(absolutePath: string, cwd: string): string",
			].join("\n"),
			declarationCount: 1,
			returnedBytes: 180,
			avoidedBytes: 220,
		},
		{
			name: "symbol",
			sampleTitle: "Declaration View",
			args: { locators: [6], view: "declaration" },
			target: "path-display.ts: formatPathForDisplay",
			options: "[declaration]",
			result: [
				"29-36(6): formatPathForDisplay",
				"export function formatPathForDisplay(absolutePath: string, cwd: string): string {",
				"\tconst relativePath = relative(cwd, absolutePath);",
				'\tif (relativePath === "" || relativePath.startsWith(".." + sep)) return absolutePath;',
				"\treturn toSlashPath(relativePath);",
				"}",
			].join("\n"),
			declarationCount: 1,
			returnedBytes: 260,
			avoidedBytes: 140,
		},
		{
			name: "symbol",
			sampleTitle: "Batch Locators",
			args: { locators: [3, 6], view: "signature" },
			target: "path-display.ts: resolveExplorePath,formatPathForDisplay",
			options: "[signature]",
			result: [
				"11-15(3): resolveExplorePath",
				"export function resolveExplorePath(cwd: string, input: string): string",
				"",
				"29-36(6): formatPathForDisplay",
				"export function formatPathForDisplay(absolutePath: string, cwd: string): string",
			].join("\n"),
			declarationCount: 2,
			returnedBytes: 240,
			avoidedBytes: 560,
		},
		{
			name: "symbol",
			sampleTitle: "Declaration With Context",
			args: { locators: [6], view: "declaration", contextLines: 1 },
			target: "path-display.ts: formatPathForDisplay",
			options: "[declaration context=1]",
			result: [
				"28-37(6): formatPathForDisplay",
				"",
				"export function formatPathForDisplay(absolutePath: string, cwd: string): string {",
				"\tconst relativePath = relative(cwd, absolutePath);",
				'\tif (relativePath === "" || relativePath.startsWith(".." + sep)) return absolutePath;',
				"\treturn toSlashPath(relativePath);",
				"}",
				"",
			].join("\n"),
			declarationCount: 1,
			returnedBytes: 290,
			avoidedBytes: 110,
		},
		{
			name: "symbol",
			sampleTitle: "Stale Locator Error",
			args: { locators: [99], view: "signature" },
			target: "99",
			options: "[signature]",
			result: "Symbol locator 99 is stale. Run outline again.",
			declarationCount: 0,
			returnedBytes: 46,
			avoidedBytes: 0,
			isError: true,
		},
	]);
}
